_type: GroundingDINOTrainingConfig

denoising_loss_cfg:
  _type: GroundingDINODenoisingLossConfig
  denoiser_cfg:
    _type: ContrastiveDenoiserConfig
    box_noise_rate: 0.4
    label_noise_rate: 0.5
    num_cdn_queries: 200
    emb_dim: 256
  set_loss_cfg:
    _type: SetLossConfig
    focal_alpha: 0.25
    focal_gamma: 2.0
    matcher_cfg:
      _type: HungarianMatcherConfig
      coef_cls: 1.0
      coef_giou: 2.0
      coef_l1: 5.0
      eps: 1.0e-05
      focal_alpha: 0.25
      focal_gamma: 2.0
    weight_cls: 2.0
    weight_giou: 2.0
    weight_l1: 5.0

detection_loss_cfg:
  _type: GroundingDINODetectionLossConfig
  set_loss_cfg:
    _type: SetLossConfig
    focal_alpha: 0.25
    focal_gamma: 2.0
    matcher_cfg:
      _type: HungarianMatcherConfig
      coef_cls: 1.0
      coef_giou: 2.0
      coef_l1: 5.0
      eps: 1.0e-05
      focal_alpha: 0.25
      focal_gamma: 2.0
    weight_cls: 2.0
    weight_giou: 2.0
    weight_l1: 5.0

lr: 0.0001
image_backbone_lr: 0.0
text_backbone_lr: 0.0
num_epochs: 12
lr_drop_step: [9, 11]
weight_decay: 0.0001
grad_clip_val: 0.1
